### ISSUE TITLE
Use a command line tool to manage glossary! ❤️

### ISSUE THREAD

**Issue by ccmywish** [tenderlove/ruby-glossary#1]
Hi Aaron!

I've developed a command line tool [cryptic resolver](https://github.com/cryptic-resolver/cr.rb) to manage all these glossary things especially for abbreviations, acronyms(initialism). 

One of the assumed target usages for this tool is to solve the problem of too many acronyms exsisting in traditional C code base. It's the root of bad intelligibility.  I'm very excited to see that what you're doing here is where this tool can help. 

I've already created a [repository](https://github.com/ccmywish/CRuby-Source-Code-Dictionary) for you to show how to use it. **If you think this is really helpful, I can transfer this repo to you for better maintenance.** 

## screenshots

<img width="307" alt="Screenshot 2023-01-25 170900" src="https://user-images.githubusercontent.com/63459097/214523115-00101db8-6ab7-4413-808f-cc628b03d40c.png">

<img width="696" alt="image" src="https://user-images.githubusercontent.com/63459097/214525796-dd4d1bd8-c6c9-4161-b86b-4dddba2ec136.png">

**Comment by tenderlove** [comment]
This is really cool, thanks for showing me this tool.  I really like the idea, but I'd rather just focus on writing the glossary than maintaining a new tool.  Thank you for the offer though, and thank you for showing me this. 🙇🏻‍♀️
