### ISSUE TITLE
Merge into ruby/ruby

### ISSUE THREAD

**Issue by casperisfine** [tenderlove/ruby-glossary#12]
Seems to me this glossary could be maintained in https://github.com/ruby/ruby/tree/master/doc

**Comment by casperisfine** [comment]
Or https://github.com/ruby/ruby/tree/master/doc/contributing more specifically.

**Comment by tenderlove** [comment]
If it seems generally helpful enough, I'll push this upstream

**Comment by tenderlove** [comment]
https://github.com/ruby/ruby/pull/7280
